### PR TITLE
Update view_in_group.py

### PR DESCRIPTION
**Pull request by mattst**
Fixed index out of range bug for view-less windows.

### CODE REVIEW

**Comment by adamchainz** [comment]
Released by tag v1.1.0, should be updated by Package Control automatically...

**Comment by mattst** [comment]
Thanks Adam. It has been updated by Package Control.

P.S. Don't forget to close the issue: https://github.com/adamchainz/SublimeSwitchViewInGroup/issues/1

**Comment by adamchainz** [comment]
Next time put the text "Fixes #X" with X replaced by the issue number and github will close it automatically on merge

**Comment by mattst** [comment]
Will do. Thanks for the hint.

**Pull request merged**
