### PR TITLE
Fix plugin to work in groups with images loaded

### PR DESCRIPTION
**Pull request by mattst**
Fixed bug - plugin fails to work properly in groups with an image loaded in ST v. 3055 and later.

### CODE REVIEW

**Comment by mattst** [comment]
By the way I tested the code on ST version 3 build 3126, and version 2 build 2221.

HTH.

**Comment by adamchainz** [comment]
Thanks, I had no idea Sublime could open images or that the API had changed from views to sheets

**Review by adamchainz — APPROVED** [review]

**Comment by adamchainz** [comment]
I guess technically the plugin should be called 'switch sheet in group' now, but can't really do that without breaking everyone's installs ;)

**Comment by mattst** [comment]
No problem. 'Group Tab Switcher' would have been my choice but as you said installs would get broken.

I only very rarely open images in ST so it was only the other day that I noticed that doing so prevented the plugin from working properly.

**Pull request merged**
